// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import * as dotenv from 'dotenv';
import { defineConfig } from "prisma/config";

// Указываем путь к .env файлу, который находится на уровень выше (в корне art_app)
dotenv.config({ path: '../.env' });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Теперь процесс увидит DATABASE_URL из корневого .env
    url: process.env.DATABASE_URL,
  },
});

